services:
  - name: api-service
    type: web
    env: docker
    dockerContext: ./api-service
    dockerfilePath: ./api-service/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: DB_HOST
        fromDatabase:
          name: news-aggregator-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: news-aggregator-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: news-aggregator-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: news-aggregator-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: news-aggregator-db
          property: database
      - key: SCRAPER_SERVICE_URL
        value: "https://scraper-service.onrender.com" # We'll use HTTP communication instead of Kafka
    healthCheckPath: /health
    numInstances: 1

  - name: scraper-service
    type: web # Changed from worker to web since free tier doesn't support background workers
    env: docker
    dockerContext: ./scraper-service
    dockerfilePath: ./scraper-service/Dockerfile
    plan: free
    envVars:
      - key: SCRAPE_INTERVAL
        value: "900" # 15 minutes to stay within free tier limits
      - key: DB_HOST
        fromDatabase:
          name: news-aggregator-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: news-aggregator-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: news-aggregator-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: news-aggregator-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: news-aggregator-db
          property: database
    numInstances: 1
    
databases:
  - name: news-aggregator-db
    type: postgres
    plan: free
    ipAllowList: []
