services:
  - type: web
    name: news-aggregator-api
    env: docker
    repo: https://github.com/thehuy1805/news-aggregator
    region: singapore
    dockerfilePath: ./api-service/Dockerfile
    plan: free
    envVars:
      - key: POSTGRES_URL
        fromDatabase:
          name: news-db
          property: connectionString
      - key: KAFKA_BROKERS
        value: ${KAFKA_URL}
    scaling:
      minInstances: 1
      maxInstances: 1
    healthCheckPath: /health

  - type: worker
    name: news-aggregator-scraper
    env: docker
    repo: https://github.com/thehuy1805/news-aggregator
    region: singapore
    dockerfilePath: ./scraper-service/Dockerfile
    plan: free
    envVars:
      - key: KAFKA_BROKERS
        value: ${KAFKA_URL}
    scaling:
      minInstances: 1
      maxInstances: 1

databases:
  - name: news-db
    plan: free
    region: singapore
    ipAllowList: []